services:
  myapp:
    container_name: crontab_myapp_1
    image: alpine:3.5
    restart: always
    command: "sh -c 'while :; do sleep 1; done'"

  crontab:
    build: .
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${PWD}/config-samples/config.sample.mapping.json:/opt/crontab/config.json:rw"
